export const DISCONNECT = "DISCONNECT";
export const FETCH_ADMIN = "FETCH_ADMIN";
export const RECEIVE_ADMIN = "RECEIVE_ADMIN";
export const UPDATED_ADMIN = "UPDATED_ADMIN";
export const FETCH_SERVER = "FETCH_SERVER";

export const PAUSED_SERVER = "PAUSED_SERVER";
export const RESUME_SERVER = "RESUME_SERVER";
export const ADDWINNER_NUMBER = "ADDWINNER_NUMBER";
export const CHECK = "CHECK";
export const WINNERS = "WINNERS";
export const PASSWINNER_SERVER = "PASSWINNER_SERVER"

